In [1]:
import cv2
import numpy as np

In [2]:
path = 'data/lena.png'

In [6]:
img = cv2.imread(path)
print(img)

[[[125 137 226]
  [125 137 226]
  [133 137 223]
  ...
  [122 148 230]
  [110 130 221]
  [ 90  99 200]]

 [[125 137 226]
  [125 137 226]
  [133 137 223]
  ...
  [122 148 230]
  [110 130 221]
  [ 90  99 200]]

 [[125 137 226]
  [125 137 226]
  [133 137 223]
  ...
  [122 148 230]
  [110 130 221]
  [ 90  99 200]]

 ...

 [[ 60  18  84]
  [ 60  18  84]
  [ 58  27  92]
  ...
  [ 84  73 173]
  [ 76  68 172]
  [ 79  62 177]]

 [[ 57  22  82]
  [ 57  22  82]
  [ 62  32  96]
  ...
  [ 79  70 179]
  [ 81  71 181]
  [ 81  74 185]]

 [[ 57  22  82]
  [ 57  22  82]
  [ 62  32  96]
  ...
  [ 79  70 179]
  [ 81  71 181]
  [ 81  74 185]]]


In [4]:
img_hsv = cv2.cvtColor(img, cv2.COLOR_BGR2HSV)

In [5]:
img_hsl = cv2.cvtColor(img, cv2.COLOR_BGR2HLS)
print(img_hsl)

[[[  4 176 162]
  [  4 176 162]
  [  1 178 149]
  ...
  [  7 176 174]
  [  5 166 158]
  [  2 145 128]]

 [[  4 176 162]
  [  4 176 162]
  [  1 178 149]
  ...
  [  7 176 174]
  [  5 166 158]
  [  2 145 128]]

 [[  4 176 162]
  [  4 176 162]
  [  1 178 149]
  ...
  [  7 176 174]
  [  5 166 158]
  [  2 145 128]]

 ...

 [[161  51 165]
  [161  51 165]
  [166  60 139]
  ...
  [177 123 104]
  [178 120 110]
  [176 120 123]]

 [[162  52 147]
  [162  52 147]
  [166  64 128]
  ...
  [178 124 112]
  [177 126 111]
  [178 130 113]]

 [[162  52 147]
  [162  52 147]
  [166  64 128]
  ...
  [178 124 112]
  [177 126 111]
  [178 130 113]]]


In [6]:
img_lab = cv2.cvtColor(img, cv2.COLOR_BGR2LAB)

In [7]:
merge_img = np.hstack((img,img_hsv,img_hsl,img_lab))

In [ ]:
cv2.imshow('作業2',merge_img)
cv2.waitKey(0)