In [1]:
import numpy as np

Affine transformation轉換公式:

$$ \vec{y}_{m×1}=A_{m×n} \cdot \vec{x}_{n×1}+ \vec{b}_{m×1} $$

※python寫數學式：https://blog.csdn.net/smilejiasmile/article/details/80670742

In [5]:
x = np.array((1,2,3))
b = np.ones(2) #產生[1,1]
A = np.random.rand(2,3)#二維陣列:2*3矩陣
y1 = np.dot(A,x) +b #上列運算式,dot為矩陣相乘,EX:y1 = array([2.8777759 , 3.04524454])

array([2.8777759 , 3.04524454])

In [8]:
z=np.array([(1,2,3),(4,5,6)])
w = np.dot(z,x) #[1*1+2*5+3*3 , 4*1+5*2+6*3] =[14,32]

array([14, 32])

轉換成如下公式：
$$ \left[\begin{matrix} \vec{y} \\ 1 \end{matrix} \right]_{(m+1)x1} =  \left[\begin{matrix} & A& & \vec{b} \\ 0,&...&,0&1  \end{matrix} \right]_{(m+1)x(n+1)} + \left[\begin{matrix} \vec{x} \\ 1 \end{matrix} \right]_{(m+1)x1}$$

In [26]:
#print("A:",A) #[[1,2,3][1,2,3]]
b_r=b.reshape(-1,1) #[[1],[1]] 轉換成2個1維陣列
A_mtx= np.hstack((A,b_r)) #[[1,2,3,1][1,2,3,1]]
#print("A_mtx:",A_mtx)
x_mtx= np.hstack( (x,1) ) #[1 2 3 1]
x_mtx_r=x_mtx.reshape(-1,1) #[[1],[2],[3],[1]]
#print("x_mtx:",x_mtx)
#print("x_mtx_r:",x_mtx_r)
zero= np.zeros(3) #[0,0,0]
zero_under=np.hstack((zero,1)) #[0. 0. 0. 1.]
zero_under_r = zero_under.reshape(1,-1) #[[0. 0. 0. 1.]]
A_mtx = np.vstack( (A_mtx,zero_under_r) ) #[[1,2,3,1][1,2,3,1][0,0,0,1]]
#print("A_mtx2:",A_mtx)
y2 = np.dot(A_mtx,x_mtx_r) #[[v1],[v2],[1]]
#print("y2:",y2)

x_mtx: [1 2 3 1]
x_mtx_r: [[1]
 [2]
 [3]
 [1]]
y2: [[2.8777759 ]
 [3.04524454]
 [1.        ]]


In [48]:
print("A.shape[0]:",A.shape[0]) #2
print("A.shape[1]:",A.shape[1]) #3
A_mtx2 = np.zeros( (A.shape[0]+1,A.shape[1]+1) ) #二維陣列，3*4
#[[0. 0. 0. 0.]
# [0. 0. 0. 0.]
# [0. 0. 0. 0.]]
A_mtx2[-1,-1] = 1 #最後一排，最後一個元素 = 1
#[[0. 0. 0. 0.]
#[0. 0. 0. 0.]
# [0. 0. 0. 1.]]
print("A:",A)
#A_mtx2=>3*4
A_mtx2[:-1,:-1]=A # = A_mtx2[:2,:3]
#print("A_mtx2:",A_mtx2)
#print("A_mtx2[:2,:3]:",A_mtx2[:2,:3]) #show 2*3
#print("A_mtx2[:-1,:-1]:",A_mtx2[:-1,:-1]) # show (3-1) * (4-1)
#print("A_mtx2[:3,:3]:",A_mtx2[:3,:3])#show 3*3
#print("b:",b)
A_mtx2[:-1,-1]=b
#print("A_mtx2:",A_mtx2)
y2 = np.dot(A_mtx2,x_mtx_r)
print("y2:",y2) #[ [v1],[v2],[1]]

A.shape[0]: 2
A.shape[1]: 3
A: [[0.03177973 0.00580705 0.61146069]
 [0.35832982 0.09036957 0.50205853]]
A_mtx2: [[0.03177973 0.00580705 0.61146069 0.        ]
 [0.35832982 0.09036957 0.50205853 0.        ]
 [0.         0.         0.         1.        ]]
A_mtx2[:2,:3]: [[0.03177973 0.00580705 0.61146069]
 [0.35832982 0.09036957 0.50205853]]
A_mtx2[:-1,:-1]: [[0.03177973 0.00580705 0.61146069]
 [0.35832982 0.09036957 0.50205853]]
A_mtx2[:3,:3]: [[0.03177973 0.00580705 0.61146069]
 [0.35832982 0.09036957 0.50205853]
 [0.         0.         0.        ]]
b: [1. 1.]
A_mtx2: [[0.03177973 0.00580705 0.61146069 1.        ]
 [0.35832982 0.09036957 0.50205853 1.        ]
 [0.         0.         0.         1.        ]]
y2: [[2.8777759 ]
 [3.04524454]
 [1.        ]]
