In [1]:
import numpy as np

In [15]:
a = np.array([1,2,3])
b = np.array([5,6,7])
c = np.array([9,10,11])

In [7]:
print(a.shape)

(3,)


In [8]:
a

array([1, 2, 3])

In [18]:
v = np.stack( (a,b,c), axis=1)
print(v)

[[ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]]


In [19]:
v = np.stack( (a,b,c), axis=-1)
print(v)

[[ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]]


In [20]:
v = np.stack( (a,b,c), axis=0)
print(v)

[[ 1  2  3]
 [ 5  6  7]
 [ 9 10 11]]


In [21]:
v = np.stack( (a,b,c), axis=2)
print(v)

AxisError: axis 2 is out of bounds for array of dimension 2